# Copy this file to `.env.yml`, and edit to taste
#
# Whenever a setting is changed here, the app process
# has to be restarted for changes to take effect.
#
# This is preferable, since we do not have to recompile the
# app to apply settings.
#
# REFERENCES:
#
# - https://github.com/grottopress/envy

lucky_env: development # Set to `production` in production

# Set this to `"true"` to make the first user
# to register an "admin"
#
# After the first user is registered, set this
# back to `"false"` and restart the app process
make_first_user_admin: 'false'

name: My App
url: http://localhost:5000

logo_url: /logo.png
favicon_url: /favicon.ico

timezone: UTC

server:
  host: '0.0.0.0'
  port: '5000'

gzip_enabled: 'false'
secret_key_base: XeqAgSy5QQ+dWe8ruOBUMrz9XPbPZ7chPVtz2ecDGss=
ssl_enabled: 'false'

assets_host: ''

database_url: postgres://postgres:password@localhost:5432/penny_development
# database_url: postgres://root@localhost:26257/penny_development?sslmode=disable

session_key: _app-session

email_from: noreply@my-app.tld
email_reply_to: support@my-app.tld

smtp:
  host: mail.example.com
  password: a1bcde234
  port: '587'

bearer_login_expiry: '7776000' # 3 months
email_confirmation_expiry: '3600' # 1 hour
login_expiry: '86400' # 1 day
login_idle_timeout: '1800' # 30 minutes
password_reset_expiry: '1800' # 30 minutes

# You should change these in production
password:
  min_length: '4'
  require_lowercase: 'false'
  require_number: 'false'
  require_special_char: 'false'
  require_uppercase: 'false'

skip_log_regex: code|password|secret|token

jobs:
  batch_size: '-1'
  poll_interval: '3' # seconds

redis_url: redis://localhost:6379/0

worker_id: '1'

keep_bearer_logins_days: '90'
keep_email_confirmations_days: '90'
keep_logins_days: '90'
keep_password_resets_days: '90'
