name: CI
on:
  push:
    paths:
      - '**.cr'
      - '.github/workflows/**'
  pull_request:
    branches: [master]
    paths:
      - '**.cr'
      - '.github/workflows/**'
  # schedule:
  #   - cron: '0 6 * * 6'
jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        crystal: [1.6.0]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards install
      - name: Lint code
        run: ./bin/ameba
  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal: [1.6.0, latest]
        experimental: [false]
        include:
          - crystal: nightly
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Cache shards
        uses: actions/cache@v3
        with:
          path: ~/.cache/shards
          key: ${{ runner.os }}-shards-${{ hashFiles('shard.yml') }}
          restore-keys: ${{ runner.os }}-shards-
      - name: Install shards
        run: shards update
      - name: Install Postgresql
        run: sudo apt -y install postgresql
      - name: Start Postgresql
        run: sudo systemctl start postgresql
      - name: Set Postgres password
        run: >-
          sudo -u postgres psql -c
          "ALTER USER postgres WITH PASSWORD 'password';"
      - name: Run tests
        env:
          APP_NAME: penny
          ASSETS_HOST: ""
          BASE_URI: http://localhost:5000
          BEARER_LOGIN_EXPIRY: "7776000" # 3 months
          DATE_FORMAT: '%d %B, %Y'
          EMAIL_FROM: noreply@my-app.tld
          EMAIL_REPLY_TO: support@my-app.tld
          GZIP_ENABLED: "false"
          DATABASE_URL: postgres://postgres:password@localhost:5432/app_development
          EMAIL_CONFIRMATION_EXPIRY: "3600" # 1 hour
          FAVICON_URL: /favicon.ico
          LOGIN_EXPIRY: "86400" # 1 day
          LOGIN_IDLE_TIMEOUT: "1800" # 30 minutes
          LOGO_URL: /logo.png
          MAKE_FIRST_USER_ADMIN: "true"
          PASSWORD_MIN_LENGTH: "4"
          PASSWORD_REQUIRE_LOWERCASE: "false"
          PASSWORD_REQUIRE_NUMBER: "false"
          PASSWORD_REQUIRE_SPECIAL_CHAR: "false"
          PASSWORD_REQUIRE_UPPERCASE: "false"
          PASSWORD_RESET_EXPIRY: "1800" # 30 minutes
          SECRET_KEY_BASE: XeqAgSy5QQ+dWe8ruOBUMrz9XPbPZ7chPVtz2ecDGss=
          SEND_GRID_KEY: unused
          SERVER_HOST: "0.0.0.0"
          SERVER_PORT: "5000"
          SESSION_KEY: _app-session
          SKIP_LOAD_ENV: "true"
          SKIP_LOG_REGEX: /password|secret|token/i
          SSL_ENABLED: "false"
          TIME_FORMAT: '%l:%M %P'
          TIMEZONE: UTC
        run: crystal spec --error-on-warnings spec/app
